/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type StyledTable = {
  _type: "styledTable";
  rows?: Array<{
    cells?: Array<{
      content?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      bgColor?: TextColor;
      textColor?: TextColor;
      _key: string;
    }>;
    _key: string;
  }>;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    _key: string;
  } & TextColor | {
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
  _key: string;
} | {
  _key: string;
} & StyledTable>;

export type Seo = {
  _type: "seo";
  seoTitle: string;
  seoDescription: string;
};

export type Link = {
  _type: "link";
  label: string;
  url: string;
  openInNewTab: boolean;
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  slug: Slug;
  title: string;
  description: string;
  heroImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  content: BlockContent;
  author: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blogAuthor";
  };
  category: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blogCategory";
  };
  uplodedAt?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type BlogAuthor = {
  _id: string;
  _type: "blogAuthor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  authorName: string;
};

export type BlogCategory = {
  _id: string;
  _type: "blogCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label: string;
  slug: Slug;
};

export type Calculator = {
  _id: string;
  _type: "calculator";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  title: string;
  icon: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  tagLine: string;
  description: string;
  slug: string;
  category: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "calculatorCategory";
  };
  aboutCalculator?: BlockContent;
};

export type TextColor = {
  _type: "textColor";
  label?: string;
  value?: string;
};

export type CalculatorCategory = {
  _id: string;
  _type: "calculatorCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  title: string;
  tagLine: string;
  slug: string;
};

export type BlogCategoryPage = {
  _id: string;
  _type: "blogCategoryPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  recommandedBlogsTitle: string;
  recommandedBlogs: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "blog";
  }>;
  otherCategoriesTitle: string;
  otherCategories: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "blogCategory";
  }>;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  heroLeftTitle: string;
  heroRightTitle: string;
  heroRightBlogs: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "blog";
  }>;
  categoryGroup: Array<{
    title: string;
    categories: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "blogCategory";
    }>;
    _key: string;
  }>;
  newsTitle: string;
  newsBackgroundImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  newsBlogs: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "blog";
  }>;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headerLogo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  headerLinks: Array<{
    _key: string;
  } & Link>;
  footerLogo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  footerLinks: Array<{
    _key: string;
  } & Link>;
};

export type HighlightColor = {
  _type: "highlightColor";
  label?: string;
  value?: string;
};

export type SimplerColor = {
  _type: "simplerColor";
  label?: string;
  value?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = StyledTable | BlockContent | Seo | Link | Blog | SanityImageCrop | SanityImageHotspot | Slug | BlogAuthor | BlogCategory | Calculator | TextColor | CalculatorCategory | BlogCategoryPage | Home | Settings | HighlightColor | SimplerColor | MediaTag | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/query.ts
// Variable: homePageQuery
// Query: *[_type == 'home' && _id == 'home'][0]{        ...,        heroRightBlogs[] -> {         ...,            heroImage{               ...,                  asset ->           },          author ->,          category ->         },        categoryGroup[]{            ...,            categories[] ->,        },        newsBlogs[] -> {          ...,          heroImage{            ...,                asset ->           },          author ->,         category ->         },        newsBackgroundImage{            ...,            asset ->,        }    }
export type HomePageQueryResult = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  heroLeftTitle: string;
  heroRightTitle: string;
  heroRightBlogs: Array<{
    _id: string;
    _type: "blog";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    seo: Seo;
    slug: Slug;
    title: string;
    description: string;
    heroImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    content: BlockContent;
    author: {
      _id: string;
      _type: "blogAuthor";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      authorName: string;
    };
    category: {
      _id: string;
      _type: "blogCategory";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      label: string;
      slug: Slug;
    };
    uplodedAt?: string;
  }>;
  categoryGroup: Array<{
    title: string;
    categories: Array<{
      _id: string;
      _type: "blogCategory";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      label: string;
      slug: Slug;
    }>;
    _key: string;
  }>;
  newsTitle: string;
  newsBackgroundImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  newsBlogs: Array<{
    _id: string;
    _type: "blog";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    seo: Seo;
    slug: Slug;
    title: string;
    description: string;
    heroImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    content: BlockContent;
    author: {
      _id: string;
      _type: "blogAuthor";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      authorName: string;
    };
    category: {
      _id: string;
      _type: "blogCategory";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      label: string;
      slug: Slug;
    };
    uplodedAt?: string;
  }>;
} | null;
// Variable: blogsByCategoryQuery
// Query: *[_type == 'blog' && category->slug.current == $categorySlug]{        ...,        heroImage{            ...,                asset ->         },        author ->,        category ->     }
export type BlogsByCategoryQueryResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  slug: Slug;
  title: string;
  description: string;
  heroImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  content: BlockContent;
  author: {
    _id: string;
    _type: "blogAuthor";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    authorName: string;
  };
  category: {
    _id: string;
    _type: "blogCategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    label: string;
    slug: Slug;
  };
  uplodedAt?: string;
}>;
// Variable: blogBySlugQuery
// Query: *[_type == 'blog' && category->slug.current == $categorySlug && slug.current == $blogSlug][0]{        ...,        heroImage{            ...,                asset ->         },        author ->,        category ->     }
export type BlogBySlugQueryResult = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  slug: Slug;
  title: string;
  description: string;
  heroImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  content: BlockContent;
  author: {
    _id: string;
    _type: "blogAuthor";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    authorName: string;
  };
  category: {
    _id: string;
    _type: "blogCategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    label: string;
    slug: Slug;
  };
  uplodedAt?: string;
} | null;
// Variable: blogCategoryBySlugQuery
// Query: *[_type == 'blogCategory' && slug.current == $categorySlug][0]{        ...,    }
export type BlogCategoryBySlugQueryResult = {
  _id: string;
  _type: "blogCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label: string;
  slug: Slug;
} | null;
// Variable: claculatorCategoriesQuery
// Query: *[_type == 'calculatorCategory']{        _id,        title,        tagLine,        slug,    }
export type ClaculatorCategoriesQueryResult = Array<{
  _id: string;
  title: string;
  tagLine: string;
  slug: string;
}>;
// Variable: calculatorQuery
// Query: *[_type == 'calculator']{        ...,        icon {            ...,            asset ->        },        category ->    }
export type CalculatorQueryResult = Array<{
  _id: string;
  _type: "calculator";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  title: string;
  icon: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  tagLine: string;
  description: string;
  slug: string;
  category: {
    _id: string;
    _type: "calculatorCategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    seo: Seo;
    title: string;
    tagLine: string;
    slug: string;
  };
  aboutCalculator?: BlockContent;
}>;
// Variable: settingsQuery
// Query: *[_id == 'settings' && _type == 'settings'][0]{        ...,        headerLogo {            ...,            asset ->{                ...            },        },        footerLogo{            ...,            asset ->{                ...            },        }    }
export type SettingsQueryResult = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headerLogo: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  headerLinks: Array<{
    _key: string;
  } & Link>;
  footerLogo: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  footerLinks: Array<{
    _key: string;
  } & Link>;
} | null;
// Variable: blogCategoriesQuery
// Query: *[_type == 'blogCategory']{        ...,    }
export type BlogCategoriesQueryResult = Array<{
  _id: string;
  _type: "blogCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label: string;
  slug: Slug;
}>;
// Variable: blogAuthorsQuery
// Query: *[_id == 'blogAuthor' && _type == 'blogAuthor']{        ...,    }
export type BlogAuthorsQueryResult = Array<{
  _id: string;
  _type: "blogAuthor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  authorName: string;
}>;
// Variable: blogCategoryPageQuery
// Query: *[_type == 'blogCategoryPage'][0]{        ...,        recommandedBlogs[] -> {            ...,            heroImage{            ...,                asset ->             },            author ->,            category ->         },        otherCategories[] -> {            ...,            'blogCount': count(*[_type == 'blog' && references(^._id)])        }    }
export type BlogCategoryPageQueryResult = {
  _id: string;
  _type: "blogCategoryPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  recommandedBlogsTitle: string;
  recommandedBlogs: Array<{
    _id: string;
    _type: "blog";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    seo: Seo;
    slug: Slug;
    title: string;
    description: string;
    heroImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    content: BlockContent;
    author: {
      _id: string;
      _type: "blogAuthor";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      authorName: string;
    };
    category: {
      _id: string;
      _type: "blogCategory";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      label: string;
      slug: Slug;
    };
    uplodedAt?: string;
  }>;
  otherCategoriesTitle: string;
  otherCategories: Array<{
    _id: string;
    _type: "blogCategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    label: string;
    slug: Slug;
    blogCount: number;
  }>;
} | null;
// Variable: blogsByTitleSlug
// Query: *[_type == 'blog' && title match $titleSlug] | order(_score desc){        _id,        title,        author->,        category->,        heroImage{            ...,            asset->        },        uploadedAt,        _updatedAt,        _score    }
export type BlogsByTitleSlugResult = Array<{
  _id: string;
  title: string;
  author: {
    _id: string;
    _type: "blogAuthor";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    authorName: string;
  };
  category: {
    _id: string;
    _type: "blogCategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    label: string;
    slug: Slug;
  };
  heroImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  uploadedAt: null;
  _updatedAt: string;
  _score: null;
}>;
// Variable: blogsQuery
// Query: *[ _type == 'blog']{        ...,        heroImage{            ...,                asset ->         },        author ->,        category ->     }
export type BlogsQueryResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  slug: Slug;
  title: string;
  description: string;
  heroImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  content: BlockContent;
  author: {
    _id: string;
    _type: "blogAuthor";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    authorName: string;
  };
  category: {
    _id: string;
    _type: "blogCategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    label: string;
    slug: Slug;
  };
  uplodedAt?: string;
}>;

