/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type StyledTable = {
  _type: "styledTable";
  rows?: Array<{
    cells?: Array<{
      content?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      bgColor?: TextColor;
      textColor?: TextColor;
      _key: string;
    }>;
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?:
        | "normal"
        | "h1"
        | "h2"
        | "h3"
        | "h4"
        | "h5"
        | "h6"
        | "blockquote"
        | "center";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        | ({
            _key: string;
          } & TextColor)
        | {
            href?: string;
            _type: "link";
            _key: string;
          }
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & StyledTable)
>;

export type Seo = {
  _type: "seo";
  seoTitle: string;
  seoDescription: string;
};

export type Link = {
  _type: "link";
  label: string;
  url: string;
  openInNewTab: boolean;
};

export type BlogAuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogAuthor";
};

export type BlogCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogCategory";
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  slug: Slug;
  title: string;
  description: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  content: BlockContent;
  author: BlogAuthorReference;
  category: BlogCategoryReference;
  uplodedAt?: string;
  postedToX?: boolean;
  xPostStatus?: string;
  orderRank?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type BlogAuthor = {
  _id: string;
  _type: "blogAuthor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  authorName: string;
  orderRank?: string;
};

export type BlogCategory = {
  _id: string;
  _type: "blogCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label: string;
  slug: Slug;
  orderRank?: string;
};

export type Calculator = {
  _id: string;
  _type: "calculator";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  calculatorName: string;
  icon: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  tagLine: string;
  description: string;
  slug: Slug;
  calculatorTitle: string;
  aboutCalculator?: BlockContent;
  orderRank?: string;
};

export type TextColor = {
  _type: "textColor";
  label?: string;
  value?: string;
};

export type CalculatorPage = {
  _id: string;
  _type: "calculatorPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  calculatorPageTitle: string;
  calculatorPageTagLine: string;
};

export type Contact_us = {
  _id: string;
  _type: "contact_us";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  contactTitle: string;
  contactDescription: string;
  formTitle: string;
};

export type BlogReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blog";
};

export type BlogCategoryPage = {
  _id: string;
  _type: "blogCategoryPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  recommandedBlogsTitle: string;
  recommandedBlogs: Array<
    {
      _key: string;
    } & BlogReference
  >;
  otherCategoriesTitle: string;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  heroLeftTitle: string;
  heroRightTitle: string;
  heroRightBlogs: Array<
    {
      _key: string;
    } & BlogReference
  >;
  categoryGroup: Array<{
    title: string;
    categories: Array<
      {
        _key: string;
      } & BlogCategoryReference
    >;
    _key: string;
  }>;
  newsTitle: string;
  newsBackgroundImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  newsBlogs: Array<
    {
      _key: string;
    } & BlogReference
  >;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headerLogo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  headerLinks: Array<
    {
      _key: string;
    } & Link
  >;
  footerLogo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  socialMediaLinks: Array<{
    logo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    url: Link;
    _key: string;
  }>;
  footerLinks: Array<
    {
      _key: string;
    } & Link
  >;
};

export type HighlightColor = {
  _type: "highlightColor";
  label?: string;
  value?: string;
};

export type SimplerColor = {
  _type: "simplerColor";
  label?: string;
  value?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | StyledTable
  | SanityImageAssetReference
  | BlockContent
  | Seo
  | Link
  | BlogAuthorReference
  | BlogCategoryReference
  | Blog
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | BlogAuthor
  | BlogCategory
  | Calculator
  | TextColor
  | CalculatorPage
  | Contact_us
  | BlogReference
  | BlogCategoryPage
  | Home
  | Settings
  | HighlightColor
  | SimplerColor
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/lib/query.ts
// Variable: homePageQuery
// Query: *[_type == 'home' && _id == 'home'][0]{        ...,        heroRightBlogs[] -> {         ...,          author ->,          category ->         },        categoryGroup[]{            ...,            categories[] ->,        },        newsBlogs[] -> {          ...,          author ->,          category ->         },    }
export type HomePageQueryResult = {
  _id: "home";
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  heroLeftTitle: string;
  heroRightTitle: string;
  heroRightBlogs: Array<{
    _id: string;
    _type: "blog";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    seo: Seo;
    slug: Slug;
    title: string;
    description: string;
    heroImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    content: BlockContent;
    author: {
      _id: string;
      _type: "blogAuthor";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      authorName: string;
      orderRank?: string;
    };
    category: {
      _id: string;
      _type: "blogCategory";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      label: string;
      slug: Slug;
      orderRank?: string;
    };
    uplodedAt?: string;
    postedToX?: boolean;
    xPostStatus?: string;
    orderRank?: string;
  }>;
  categoryGroup: Array<{
    title: string;
    categories: Array<{
      _id: string;
      _type: "blogCategory";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      label: string;
      slug: Slug;
      orderRank?: string;
    }>;
    _key: string;
  }>;
  newsTitle: string;
  newsBackgroundImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  newsBlogs: Array<{
    _id: string;
    _type: "blog";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    seo: Seo;
    slug: Slug;
    title: string;
    description: string;
    heroImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    content: BlockContent;
    author: {
      _id: string;
      _type: "blogAuthor";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      authorName: string;
      orderRank?: string;
    };
    category: {
      _id: string;
      _type: "blogCategory";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      label: string;
      slug: Slug;
      orderRank?: string;
    };
    uplodedAt?: string;
    postedToX?: boolean;
    xPostStatus?: string;
    orderRank?: string;
  }>;
} | null;

// Source: sanity/lib/query.ts
// Variable: blogsByCategoryQuery
// Query: *[_type == 'blog' && category->slug.current == $categorySlug]{        ...,        author ->,        category ->     }
export type BlogsByCategoryQueryResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  slug: Slug;
  title: string;
  description: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  content: BlockContent;
  author: {
    _id: string;
    _type: "blogAuthor";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    authorName: string;
    orderRank?: string;
  };
  category: {
    _id: string;
    _type: "blogCategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    label: string;
    slug: Slug;
    orderRank?: string;
  };
  uplodedAt?: string;
  postedToX?: boolean;
  xPostStatus?: string;
  orderRank?: string;
}>;

// Source: sanity/lib/query.ts
// Variable: blogBySlugQuery
// Query: *[_type == 'blog' && slug.current == $blogSlug][0]{        ...,        author ->,        category ->     }
export type BlogBySlugQueryResult = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  slug: Slug;
  title: string;
  description: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  content: BlockContent;
  author: {
    _id: string;
    _type: "blogAuthor";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    authorName: string;
    orderRank?: string;
  };
  category: {
    _id: string;
    _type: "blogCategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    label: string;
    slug: Slug;
    orderRank?: string;
  };
  uplodedAt?: string;
  postedToX?: boolean;
  xPostStatus?: string;
  orderRank?: string;
} | null;

// Source: sanity/lib/query.ts
// Variable: blogCategoryBySlugQuery
// Query: *[_type == 'blogCategory' && slug.current == $categorySlug][0]{        ...,    }
export type BlogCategoryBySlugQueryResult = {
  _id: string;
  _type: "blogCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label: string;
  slug: Slug;
  orderRank?: string;
} | null;

// Source: sanity/lib/query.ts
// Variable: calculatorsQuery
// Query: *[_type == 'calculator']{    ...,}
export type CalculatorsQueryResult = Array<{
  _id: string;
  _type: "calculator";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  calculatorName: string;
  icon: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  tagLine: string;
  description: string;
  slug: Slug;
  calculatorTitle: string;
  aboutCalculator?: BlockContent;
  orderRank?: string;
}>;

// Source: sanity/lib/query.ts
// Variable: calculatorPageQuery
// Query: *[_type == 'calculatorPage'][0]{    ...,    "calculatorList": *[_type == 'calculator']{        _id,        icon,        calculatorName,        description,        slug,    }}
export type CalculatorPageQueryResult = {
  _id: string;
  _type: "calculatorPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  calculatorPageTitle: string;
  calculatorPageTagLine: string;
  calculatorList: Array<{
    _id: string;
    icon: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    calculatorName: string;
    description: string;
    slug: Slug;
  }>;
} | null;

// Source: sanity/lib/query.ts
// Variable: calculatorBySlugQuery
// Query: *[_type == 'calculator' && slug.current == $calculatorSlug][0]{        ...,    }
export type CalculatorBySlugQueryResult = {
  _id: string;
  _type: "calculator";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  calculatorName: string;
  icon: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  tagLine: string;
  description: string;
  slug: Slug;
  calculatorTitle: string;
  aboutCalculator?: BlockContent;
  orderRank?: string;
} | null;

// Source: sanity/lib/query.ts
// Variable: settingsQuery
// Query: *[_id == 'settings' && _type == 'settings'][0]{        ...,    }
export type SettingsQueryResult = {
  _id: "settings";
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headerLogo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  headerLinks: Array<
    {
      _key: string;
    } & Link
  >;
  footerLogo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  socialMediaLinks: Array<{
    logo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    url: Link;
    _key: string;
  }>;
  footerLinks: Array<
    {
      _key: string;
    } & Link
  >;
} | null;

// Source: sanity/lib/query.ts
// Variable: blogCategoriesQuery
// Query: *[_type == 'blogCategory']{        ...,    }
export type BlogCategoriesQueryResult = Array<{
  _id: string;
  _type: "blogCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label: string;
  slug: Slug;
  orderRank?: string;
}>;

// Source: sanity/lib/query.ts
// Variable: blogAuthorsQuery
// Query: *[_id == 'blogAuthor' && _type == 'blogAuthor']{        ...,    }
export type BlogAuthorsQueryResult = Array<{
  _id: "blogAuthor";
  _type: "blogAuthor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  authorName: string;
  orderRank?: string;
}>;

// Source: sanity/lib/query.ts
// Variable: blogCategoryPageQuery
// Query: *[_type == 'blogCategoryPage'][0]{        ...,        recommandedBlogs[] -> {            ...,            author ->,            category ->         },        "category": *[_type == 'blogCategory' && slug.current == $categorySlug][0]{...,},        "blogList": *[_type == 'blog' && category->slug.current == $categorySlug]{            ...,            category->,            author->,        },        "otherCategories": *[ _type == 'blogCategory' && slug.current != $categorySlug]{            ...,            'blogCount': count(*[_type == 'blog' && references(^._id)])        }    }
export type BlogCategoryPageQueryResult = {
  _id: string;
  _type: "blogCategoryPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  recommandedBlogsTitle: string;
  recommandedBlogs: Array<{
    _id: string;
    _type: "blog";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    seo: Seo;
    slug: Slug;
    title: string;
    description: string;
    heroImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    content: BlockContent;
    author: {
      _id: string;
      _type: "blogAuthor";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      authorName: string;
      orderRank?: string;
    };
    category: {
      _id: string;
      _type: "blogCategory";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      label: string;
      slug: Slug;
      orderRank?: string;
    };
    uplodedAt?: string;
    postedToX?: boolean;
    xPostStatus?: string;
    orderRank?: string;
  }>;
  otherCategoriesTitle: string;
  category: {
    _id: string;
    _type: "blogCategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    label: string;
    slug: Slug;
    orderRank?: string;
  } | null;
  blogList: Array<{
    _id: string;
    _type: "blog";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    seo: Seo;
    slug: Slug;
    title: string;
    description: string;
    heroImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    content: BlockContent;
    author: {
      _id: string;
      _type: "blogAuthor";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      authorName: string;
      orderRank?: string;
    };
    category: {
      _id: string;
      _type: "blogCategory";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      label: string;
      slug: Slug;
      orderRank?: string;
    };
    uplodedAt?: string;
    postedToX?: boolean;
    xPostStatus?: string;
    orderRank?: string;
  }>;
  otherCategories: Array<{
    _id: string;
    _type: "blogCategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    label: string;
    slug: Slug;
    orderRank?: string;
    blogCount: number;
  }>;
} | null;

// Source: sanity/lib/query.ts
// Variable: blogsByTitleSlug
// Query: *[_type == 'blog' && title match $titleSlug + '*'] | order(_score desc){        _id,        title,        author->,        category->,        slug,        heroImage,        uploadedAt,        _updatedAt,        _score    }
export type BlogsByTitleSlugResult = Array<{
  _id: string;
  title: string;
  author: {
    _id: string;
    _type: "blogAuthor";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    authorName: string;
    orderRank?: string;
  };
  category: {
    _id: string;
    _type: "blogCategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    label: string;
    slug: Slug;
    orderRank?: string;
  };
  slug: Slug;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  uploadedAt: null;
  _updatedAt: string;
  _score: null;
}>;

// Source: sanity/lib/query.ts
// Variable: blogsQuery
// Query: *[ _type == 'blog'] | order(coalesce(uploadedAt, _createdAt) desc){        ...,        author ->,        category ->     }
export type BlogsQueryResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  slug: Slug;
  title: string;
  description: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  content: BlockContent;
  author: {
    _id: string;
    _type: "blogAuthor";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    authorName: string;
    orderRank?: string;
  };
  category: {
    _id: string;
    _type: "blogCategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    label: string;
    slug: Slug;
    orderRank?: string;
  };
  uplodedAt?: string;
  postedToX?: boolean;
  xPostStatus?: string;
  orderRank?: string;
}>;

// Source: sanity/lib/query.ts
// Variable: blogsRssQuery
// Query: *[_type == 'blog'] | order(orderrank){        title,        description,        uplodedAt,        slug,        _createdAt,        category -> ,        heroImage,    }
export type BlogsRssQueryResult = Array<{
  title: string;
  description: string;
  uplodedAt: string | null;
  slug: Slug;
  _createdAt: string;
  category: {
    _id: string;
    _type: "blogCategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    label: string;
    slug: Slug;
    orderRank?: string;
  };
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
}>;

// Source: sanity/lib/query.ts
// Variable: contactPageQuery
// Query: *[_type == 'contact_us' && _id == 'contact_us'][0]{        ...,    }
export type ContactPageQueryResult = {
  _id: "contact_us";
  _type: "contact_us";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  contactTitle: string;
  contactDescription: string;
  formTitle: string;
} | null;

// Source: sanity/lib/query.ts
// Variable: siteMapQuery
// Query: *[_type == 'blogCategory']{        _id,        "title": label,        "slug": slug.current,        "blogs": *[_type == "blog" && references(^._id)]{            title,            "slug": slug.current,            "categorySlug": category->slug.current,            _updatedAt        }    }
export type SiteMapQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  blogs: Array<{
    title: string;
    slug: string;
    categorySlug: string;
    _updatedAt: string;
  }>;
}>;
